### ISSUE TITLE
scripts/cms_equaliser doen't work in numba setup

### ISSUE THREAD

**Issue by rwaegema** [ChalmersPhotonicsLab/QAMpy#10]
When trying to run demoscript cms_equaliser, noticed the folowing issue which I think will only show up if you  try to run it in an environment with numba instead of cython:

1) qampy/core/equalisation/numba_equalisation.py
line 71
from qampy.core.equalisation.equaliser_numba Import ...
should it be ?:
from qampy.core.equalisation.numba_equalisation import ...

2) qampy/core/equalisation/numba_equalisation.py
line 131
return err, wx
Should it be ?:
return err, wx, mu
Otherwise amount of arguments don't fit when called (not 100% sure if mu is what you want to return as third argument) 

3) scripts/cma_equaliser.py
line 25, 25 
E = equalisation.apply_filter(SS,  wxy)
E_m = equalisation.apply_filter(SS, wxy_m)
I replaced by (but now cython env will not work !.)
E = equalisation.apply_filter(SS,  wxy, method='py')
E_m = equalisation.apply_filter(SS, wxy_m, method='py')
There is no detection of the numba/cython situation and passing this on to underlying function. This so the correct implementation of the function is used (can understand fully this is maybe not priority 1 for you...) Maybe a variable method in main script set to is py or pyx and a passed on if needed would already improve on this ...

**Comment by cycomanic** [comment]
Thanks for reporting. The numba engine actually has seen little love recently, so this probably came with one of the updates on the cython backend. I'll look into this.  As a side note, I'm thinking about removing the numba engine, it is orders of magnitude slower and currently only adds confusion when it's being used instead of the cython backend

**Comment by cycomanic** [comment]
I have fixed issue 2, however I could not find issue 1 (nowhere in the code is a upper case Import) are you using the a checked out version?

Also I am working on providing some precompiled packages for windows.

**Comment by rwaegema** [comment]
Sorry mixed things up a bit in 1.: the file is actually  \qampy\core\equalisation\equalisation.py  and it's line 72 (import of the module qampy/core/equalisation/numba_equalisation.py) The uppercase import is a typo from me, it is lowercase in your script. The main issue I wanted to report  is replacing 'equaliser_numba' with 'numba_equalisation' .
