### ISSUE TITLE
QAMpy/signals no class QAMmodulator

### ISSUE THREAD

**Issue by kevinclily** [ChalmersPhotonicsLab/QAMpy#11]
Hi,

While running the scripts I found lots of the scripts (for example, mrde_equalizer.py) relied on signals.QAMmodulator. But I didn't find it. Is this part not attached?

Thanks.

**Comment by cycomanic** [comment]
Ah some of the scripts have not been updated to work with the most recent API. I will do a clean up in the next weeks to fix this.

**Comment by kevinclily** [comment]
> Ah some of the scripts have not been updated to work with the most recent API. I will do a clean up in the next weeks to fix this.

Hi Thanks for your reply. Is it ready? I pulled the dir again but still missed the model.

Thanks!

**Comment by cycomanic** [comment]
Hi @kevinclily ,

sorry we've been busy with quite a few other things, so haven't gotten around to this yet. We have a retreat planned for the beginning of october where we wanto clean up a number of things and this is the highest priority. So we'll have it done by then.

**Comment by arkountos** [comment]
This is still an issue!

**Comment by luizwurlitzer** [comment]
This is still an issue we need it so much.

**Comment by brenodl** [comment]
coloca a porra do QAMModulator arrombado.

**Comment by brenodl** [comment]
puts the fucking QAMModulator broken into.

**Comment by cycomanic** [comment]
@kevinclily @arkountos @luizwurlitzer this should be fixed now, sorry forgot to push a private repository. Just a heads up though the underlying libraries will soon change from cython to pythran
