### ISSUE TITLE
Detailed Windows install instructions

### ISSUE THREAD

**Issue by bbgra** [ChalmersPhotonicsLab/QAMpy#12]
Hi,

I just saw that detailed install instructions for Windows are missing. Since I just completed this and managed to run the example scripts, I thought I would share it.

Setup:
- Windows 7
- conda

Create a conda environment with python 3.6 (also tested for 3.5):
`conda create --name myenv python=3.6`
`conda activate myenv`

Install the dependencies:
`conda install numpy scipy cython bitarray numba matplotlib hdf5`

Note that matplotlib and hdf5 are not listed as requirements but needed for running the examples. Missing hdf5 will give you a very cryptic error about missing dlls on windows.

Now we need to install the same Visual Studio version as python was compiled with. In this case, it is Visual Studio 2015 Community Edition. You can download it here: https://visualstudio.microsoft.com/downloads/.
When installing it, make sure to select custom installation and enable the C++ language. 

Go back to the QAMpy folder and run 
`python setup.py build`
`python setup.py install`

Test if everything works by running a script in the scripts-subfolder.
Done.

Maybe this is of help to some.

BR
Andreas

**Comment by Jarred27** [comment]
Hi there,

thank you for commenting about installing on windows, this has been super helpful. I am wanting to test if the QAMpy library works with some data I have, but after attempting to run a few of the scripts in the 'Scripts' subfolder, I get the same error message: "Could not load any of ['hdf5.dll', 'hdf5dll.dll'], please ensure that it can be found in the system path".

from a small search, it seems that the "hdf5" library has been renamed to h5py in the PyPI.org site. Do you have any simple help, tips or tricks to get this working? 
Thanks!

**Comment by cycomanic** [comment]
Hi @Jarred27 ,

yes there's still some old scripts relying on hd5, we since moved to use a different way of saving data. I've actually some branch where a did a bit of a clean up I will try to push this in the next weeks. For now I recommend to simply no worry about those scripts.

**Comment by Jarred27** [comment]
Hi @cycomanic ,

it seems like you've done a lot of hard work, so it would be cool to try it and see how it works! thanks.

**Comment by alphalzZ** [comment]
Thanks for sharing the experience, I have been running the example and the result has been mysterious errors. Now I am not worried about that.
