### ISSUE TITLE
sync2frame() issue with PilotBased Demo

### ISSUE THREAD

**Issue by AaronCUbIQ** [ChalmersPhotonicsLab/QAMpy#14]
Hi,

After running the PilotBasedDSP_SignalObjectDemo notebook I've encountered the following error message.
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-30-c169e1a857b0> in <module>
----> 1 mysig3.sync2frame()

AttributeError: 'NoneType' object has no attribute 'sync2frame'
----------------------------------------------------------------------------
Have you encountered similar issues with sync2frame? Could you please help me out with this?

Thanks,
P.S. I'm using python 3.6.8.

**Comment by cycomanic** [comment]
OK this seems to be an issue in the PMD simulator (not sure when we introduced it). For now to test you can simply set the DGD to None in the `simulate_transmission` function in the cell above. I will fix this in the meantime.

**Comment by cycomanic** [comment]
@AaronCUbIQ this is fixed now, thanks for reporting
