### ISSUE TITLE
About QAMpy deployment

### ISSUE THREAD

**Issue by JefFan4YC** [ChalmersPhotonicsLab/QAMpy#17]
Hi, @cycomanic 

After self-building the required virtual env, I met a similar issue as: #15 
[https://github.com/ChalmersPhotonicsLab/QAMpy/issues/15#issuecomment-1198378112](url)

For details, I followed the steps in [http://qampy.org/installation/windows.html](url)
`conda install numpy scipy`
`conda install -c conda-forge pythran`
Installed VS Community Desktop C++, Python Packs (ver. 2019 & 2022 tested)
`conda install -c conda-forge clang`
`python setup.py build`

Then, the error `No module named ‘numpy.distutils._msvccompiler‘ in numpy.distutils; trying from distutils` came out. 
May I know some tips to solve this? Thanks.

**Comment by JefFan4YC** [comment]
The logging shows:

> (QAMpy) PS C:\Users\RaymondYin\Downloads\JianGuoCloud\Research\Codes\QAMpy> python setup.py build
WARNING: Failed to find 'pythran-openblas' package. Please install it or change the compiler.blas setting. Defaulting to 'blas'
running build
running build_py
running egg_info
writing qampy.egg-info\PKG-INFO
writing dependency_links to qampy.egg-info\dependency_links.txt
writing requirements to qampy.egg-info\requires.txt
writing top-level names to qampy.egg-info\top_level.txt
reading manifest file 'qampy.egg-info\SOURCES.txt'
writing manifest file 'qampy.egg-info\SOURCES.txt'
running build_ext
INFO: No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils

and clang-cl.exe is in `"C:\Users\RaymondYin\anaconda3\envs\QAMpy\Library\bin\clang-cl.exe"`

**Comment by cycomanic** [comment]
Have you activated the QAMpy (`conda activate QAMpy`) anaconda environment when you compile? Alternatively can you add `C:\Users\RaymondYin\anaconda3\envs\QAMpy\Library\bin` to your system path (under windows settings system environment variables or so)?

**Comment by JefFan4YC** [comment]
I've tried to activate my virtual env both in Pycharm console & Anaconda powershell, and the system variables have also been added, but the error kept the same.
![image](https://user-images.githubusercontent.com/75775590/234544604-ac5ee3e2-4948-449e-b76d-9394d5ce3276.png)
![image](https://user-images.githubusercontent.com/75775590/234545391-6577934d-4ff5-4beb-bc9f-7d9c0bec3c2b.png)

**Comment by JefFan4YC** [comment]
The whole cmd is long, but seems successful? Not sure.

[python setup.py install.txt](https://github.com/ChalmersPhotonicsLab/QAMpy/files/11331717/python.setup.py.install.txt)

**Comment by JefFan4YC** [comment]
Yep, I've tested 32 & 64_qam_equalisation.py and they're working well. Again, thanks for your kindly help and impressive work!
