### ISSUE TITLE
core/phaserecovery.py relies on numba

### ISSUE THREAD

**Issue by marbre** [ChalmersPhotonicsLab/QAMpy#2]
Following the README it seems like there should no hard dependency on numba  (mentioned as a fall-back option). However, in the phase recovery it is always imported:
https://github.com/ChalmersPhotonicsLab/QAMpy/blob/f7d5a274594cb01795015053cc3944de55dfa3d7/qampy/core/phaserecovery.py#L26
As a result the test scripts currently fail on my system not having numba installed.

The `bps_twostage()` function, for which also an arrayfire implementation is available, calls `select_angles()`, whose function definition is preceded by a numba jit statement. I am not sure if it is really the intention to use arrayfire and numba, thus numba might only be an optional dependency.

**Comment by cycomanic** [comment]
Ah yes, this is a leftover when I was testing both numba and arrayfire. I will need to go over this. The numba code is really only there for quick prototyping, it's been on my todo to really check that it is really optional. Thanks for reporting.
