### ISSUE TITLE
Specify minimum numba version

### ISSUE THREAD

**Issue by marbre** [ChalmersPhotonicsLab/QAMpy#3]
With numba 0.27 installed (the current stable version on Gentoo), some function required by QAMpy are not available. Installing numba 0.37 fixes this. It would be nice to add an optional dependency specifying the minimal required version to the setup.py or to mention it e.g. in the README.

**Comment by cycomanic** [comment]
Good point, I'll look into that

**Comment by marbre** [comment]
Fixed with https://github.com/ChalmersPhotonicsLab/QAMpy/commit/3b59847e5b2432224d41c829ee5ac0a267ae393a.
